name: Build & Test
on:
  - push
  - pull_request

jobs:
  macOS:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: .github/xcodebuild test macOS
  iOS:
    name: Test iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: .github/xcodebuild test iOS "iPhone"
  tvOS:
    name: Test tvOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: .github/xcodebuild test tvOS "Apple TV"
  watchOS:
    name: Build watchOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: .github/xcodebuild build watchOS "Apple Watch"

  spm-macOS:
    name: Test Swift Package manager (macOS)
    runs-on: macos-latest    
    needs:
      - macOS
    steps:
      - uses: actions/checkout@v1
      - name: swift test
        run: swift test