name: Build & Test
on:
  - push
  - pull_request

jobs:
  macOS:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: .github/xcodebuild Futures.xcodeproj "Futures macOS" test
  iOS:
    name: Test iOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: .github/xcodebuild Futures.xcodeproj "Futures iOS" test iPhone
  tvOS:
    name: Test tvOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: .github/xcodebuild Futures.xcodeproj "Futures tvOS" test "Apple TV"
  watchOS:
    name: Build watchOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: .github/xcodebuild Futures.xcodeproj "Futures watchOS" build

  spm-macOS:
    name: Test Swift Package manager (macOS)
    runs-on: macos-latest    
    needs:
      - macOS
    steps:
      - uses: actions/checkout@v1
      - name: swift test
        run: swift test