name: "Tests"

on: 
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  macOS_5_2:
    name: Test macOS (5.2)
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: macOS
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Futures.xcodeproj" -scheme "Futures-Package" -destination "platform=macOS" clean test | xcpretty
  Catalyst:
    name: Test Catalyst 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Catalyst
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Futures.xcodeproj" -scheme "Futures-Package" -destination "platform=macOS" clean test | xcpretty
  iOS:
    name: Test iOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.4.1,name=iPhone 11 Pro"] #, "OS=12.4,name=iPhone XS", "OS=11.4,name=iPhone X", "OS=10.3.1,name=iPhone SE"]
    steps:
      - uses: actions/checkout@v2
      - name: iOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Futures.xcodeproj" -scheme "Futures-Package" -destination "${{ matrix.destination }}" clean test | xcpretty
  tvOS:
    name: Test tvOS 
    runs-on: macOS-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
    strategy:
      matrix:
        destination: ["OS=13.4,name=Apple TV 4K"] #, "OS=11.4,name=Apple TV 4K", "OS=10.2,name=Apple TV 1080p"]
    steps:
      - uses: actions/checkout@v2
      - name: tvOS - ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -project "Futures.xcodeproj" -scheme "Futures-Package" -destination "${{ matrix.destination }}" clean test | xcpretty
  spm:
    name: Test with SPM
    runs-on: macOS-latest    
    env: 
      DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: SPM Test
        run: swift test -c debug